name: Hash functions
on: push
jobs:
  hash:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: echo "${HASH}"  # ログ出力はマスクされるため、実際の値は表示されない
        env:
          HASH: ${{ hashFiles('.github/workflows/*.yml') }}  # ワークフローファイルのハッシュ値を環境変数に設定