name: Secrets
on: push
jobs:
  print:
    runs-on: ubuntu-latest
    env:
      PASSWORD: ${{ secrets.PASSWORD }}  # GitHub Secretsから環境変数を定義
    steps:
      - run: echo "${PASSWORD}"  # ログ出力はマスクされるため、実際の値は表示されない
      - run: echo "${PASSWORD:0:1}　${PASSWORD#?}"  # 最初の文字だけ表示して残りをマスクする例